import {
  AliasPiece,
  ApplicationCommandRegistry,
  Args,
  ChatInputCommandContext,
  Command as SapphireCommand,
  container,
  type CommandJSON,
  type CommandOptionsRunType,
  type CommandRunInUnion,
  type CommandSpecificRunIn,
} from '@sapphire/framework';
import {
  Subcommand as SapphirePluginSubcommand,
  type SubcommandOptions,
} from '@sapphire/plugin-subcommands';
import { RegisterSubcommandsHooks } from '../utils/const.js';
import {
  analizeSubcommandGroupParsed,
  analizeSubCommandParsed,
  parseSlashSubcommand,
  subCommandsRegistry,
} from '../utils/functions.js';
import type { CommandOptions } from '../utils/types.js';
import type { CacheType } from 'discord.js';

export class Command<
  PreParseReturn extends Args = Args,
  Options extends CommandOptions & SapphireCommand.Options = CommandOptions &
    SapphireCommand.Options,
> extends SapphireCommand<PreParseReturn, Options> {
  public constructor(context: Command.LoaderContext, options: Command.Options) {
    let nameCommand = options.name;

    if (
      options.registerSubCommand &&
      container.client.options.subcommandsAdvanced?.nameCommandsAutogenerated === true
    ) {
      const slashSubcommandParsed = parseSlashSubcommand(
        options.registerSubCommand.slashSubcommand
      );
      if (slashSubcommandParsed) {
        nameCommand = `${options.registerSubCommand.parentCommandName}/${slashSubcommandParsed.name}`;
      } else nameCommand = `${options.registerSubCommand.parentCommandName}/${options.name}`;
    }

    if (
      options.registerSubcommandInGroup &&
      container.client.options.subcommandsAdvanced?.nameCommandsAutogenerated === true
    ) {
      const slashSubcommandParsed = parseSlashSubcommand(
        options.registerSubcommandInGroup.slashSubcommand
      );
      if (slashSubcommandParsed) {
        nameCommand = `${options.registerSubcommandInGroup.parentCommandName}/${options.registerSubcommandInGroup.groupName}/${slashSubcommandParsed.name}`;
      } else
        nameCommand = `${options.registerSubcommandInGroup.parentCommandName}/${options.registerSubcommandInGroup.groupName}/${options.name}`;
    }

    super(context, { ...options, name: nameCommand } as Options);

    if (this.options.registerSubCommand) {
      const { parentCommandName, slashSubcommand } = this.options.registerSubCommand;
      analizeSubCommandParsed(this, parentCommandName, slashSubcommand);
    }

    if (this.options.registerSubcommandInGroup) {
      const { parentCommandName, groupName, slashSubcommand } =
        this.options.registerSubcommandInGroup;
      analizeSubcommandGroupParsed(this, parentCommandName, groupName, slashSubcommand);
    }
  }
}

// eslint-disable-next-line no-redeclare
export namespace Command {
  export type Options = CommandOptions & SapphireCommand.Options;
  export type JSON = CommandJSON;
  /** @deprecated Use {@linkcode LoaderContext} instead. */
  export type Context = LoaderContext;
  export type LoaderContext = AliasPiece.LoaderContext<'commands'>;
  export type RunInTypes = CommandOptionsRunType;
  export type RunInUnion = CommandRunInUnion;
  export type SpecificRunIn = CommandSpecificRunIn;
  export type ChatInputCommandInteraction<Cached extends CacheType = CacheType> =
    SapphireCommand.ChatInputCommandInteraction<Cached>;
  export type ContextMenuCommandInteraction<Cached extends CacheType = CacheType> =
    SapphireCommand.ContextMenuCommandInteraction<Cached>;
  export type AutocompleteInteraction<Cached extends CacheType = CacheType> =
    SapphireCommand.AutocompleteInteraction<Cached>;
  export type Registry = ApplicationCommandRegistry;
}

export class Subcommand extends SapphirePluginSubcommand {
  public hooks = RegisterSubcommandsHooks;

  public constructor(context: SapphireCommand.LoaderContext, options: SubcommandOptions) {
    // Automatically populate subcommands from registry if this is a parent command
    const commandName = options.name;
    if (commandName && !options.subcommands) {
      const registeredSubcommands = subCommandsRegistry.get(commandName);
      if (registeredSubcommands && registeredSubcommands.size > 0) {
        const subcommandsConfig = Array.from(registeredSubcommands.values()).map(
          ({ slashCommand, commandPiece }) => ({
            name: slashCommand?.name ?? commandPiece.name,
            chatInputRun: async (
              interaction: Subcommand.ChatInputCommandInteraction,
              context: ChatInputCommandContext
            ) => {
              // Automatically route to the child command's chatInputRun
              if (commandPiece.chatInputRun) {
                return commandPiece.chatInputRun(interaction, context);
              }
              // Fallback if chatInputRun doesn't exist
              return interaction.reply({
                content: 'This subcommand is not yet implemented.',
                ephemeral: true,
              });
            },
          })
        );

        options = { ...options, subcommands: subcommandsConfig };
      }
    }

    super(context, options);
  }
}

// eslint-disable-next-line no-redeclare
export namespace Subcommand {
  export type Options = SubcommandOptions;
  export type JSON = SapphireCommand.JSON;
  /** @deprecated Use {@linkcode LoaderContext} instead. */
  export type Context = LoaderContext;
  export type LoaderContext = SapphireCommand.LoaderContext;
  export type RunInTypes = SapphireCommand.RunInTypes;
  export type ChatInputCommandInteraction<Cached extends CacheType = CacheType> =
    SapphireCommand.ChatInputCommandInteraction<Cached>;
  export type ContextMenuCommandInteraction<Cached extends CacheType = CacheType> =
    SapphireCommand.ContextMenuCommandInteraction<Cached>;
  export type AutocompleteInteraction<Cached extends CacheType = CacheType> =
    SapphireCommand.AutocompleteInteraction<Cached>;
  export type Registry = SapphireCommand.Registry;
}
